name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create task in tracker
        run: sh ./.github/create-task.sh
        env:
          OAuth: ${{ secrets.TRACKER_ACCESS_TOKEN }}
          OrganizationId: ${{ secrets.ORGANIZATION_ID}}
